### ISSUE TITLE
Error at Migrations in Mysql database

### ISSUE THREAD

**Issue by deivisonrpg** [aspnetboilerplate/module-zero-template#24]
Hi, first all thanks for this amazing job.
My problem is that I got an error when I Update-Database with a MySQL connector, I get a : 
Cannot drop index 'IX_UserId': needed in a foreign key constraint

```javascript
Applying explicit migration: 201512241148372_Created_Indexes.
alter table `AbpPermissions` drop index `IX_UserId`
MySql.Data.MySqlClient.MySqlException (0x80004005): Cannot drop index 'IX_UserId': needed in a foreign key constraint
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   at System.Data.Entity.Migrations.DbMigrator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClass30.<ExecuteStatements>b__2e()
   at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute(Action operation)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.ExecuteStatements(IEnumerable`1 migrationStatements)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClassc.<Update>b__b()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update(String targetMigration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.UpdateRunner.Run()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Cannot drop index 'IX_UserId': needed in a foreign key constraint 
```

This error appears because mysql need Remove foreign key constraint first and then drop index.
How resolve this?
Thanks

**Comment by deivisonrpg** [comment]
To solve this i modify 201512241148372_Created_Indexes.cs in up method to run CreateIndex() first then DropIndex().
ex:
```c#
namespace AbpCompanyName.AbpProjectName.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Created_Indexes : DbMigration
    {
        public override void Up()
        {
            CreateIndex("AbpAuditLogs", new[] { "TenantId", "ExecutionTime" });
            CreateIndex("AbpAuditLogs", new[] { "UserId", "ExecutionTime" });
            CreateIndex("AbpPermissions", new[] { "UserId", "Name" });
            CreateIndex("AbpPermissions", new[] { "RoleId", "Name" });
            CreateIndex("AbpRoles", new[] { "TenantId", "Name" });
            CreateIndex("AbpRoles", new[] { "IsDeleted", "TenantId", "Name" });
            CreateIndex("AbpSettings", new[] { "TenantId", "Name" });
            CreateIndex("AbpSettings", new[] { "UserId", "Name" });
            CreateIndex("AbpTenants", new[] { "TenancyName" });
            CreateIndex("AbpTenants", new[] { "IsDeleted", "TenancyName" });
            CreateIndex("AbpUserLogins", new[] { "UserId", "LoginProvider" });
            CreateIndex("AbpUserRoles", new[] { "UserId", "RoleId" });
            CreateIndex("AbpUserRoles", new[] { "RoleId" });
            CreateIndex("AbpUsers", new[] { "TenantId", "UserName" });
            CreateIndex("AbpUsers", new[] { "TenantId", "EmailAddress" });
            CreateIndex("AbpUsers", new[] { "IsDeleted", "TenantId", "UserName" });
            CreateIndex("AbpUsers", new[] { "IsDeleted", "TenantId", "EmailAddress" });

            CreateIndex("AbpOrganizationUnits", new[] { "TenantId", "ParentId" });
            CreateIndex("AbpOrganizationUnits", new[] { "TenantId", "Code" });

            CreateIndex("AbpUserOrganizationUnits", new[] { "TenantId", "UserId" });
            CreateIndex("AbpUserOrganizationUnits", new[] { "TenantId", "OrganizationUnitId" });
            CreateIndex("AbpUserOrganizationUnits", new[] { "UserId" });
            CreateIndex("AbpUserOrganizationUnits", new[] { "OrganizationUnitId" });

            CreateIndex("AbpLanguages", new[] { "TenantId", "Name" });

            CreateIndex("AbpLanguageTexts", new[] { "TenantId", "LanguageName", "Source", "Key" });

            CreateIndex("AbpEditions", new[] { "Name" });

            CreateIndex("AbpFeatures", new[] { "Discriminator", "TenantId", "Name" });
            CreateIndex("AbpFeatures", new[] { "Discriminator", "EditionId", "Name" });
            CreateIndex("AbpFeatures", new[] { "TenantId", "Name" });

            DropIndex("AbpPermissions", new[] { "UserId" });
            DropIndex("AbpPermissions", new[] { "RoleId" });
            DropIndex("AbpRoles", new[] { "TenantId" });
            DropIndex("AbpSettings", new[] { "TenantId" });
            DropIndex("AbpSettings", new[] { "UserId" });
            DropIndex("AbpUserLogins", new[] { "UserId" });
            DropIndex("AbpUserRoles", new[] { "UserId" });
            DropIndex("AbpUsers", new[] { "TenantId" });

        }

        public override void Down()
        {
            DropIndex("AbpFeatures", new[] { "TenantId", "Name" });
            DropIndex("AbpFeatures", new[] { "Discriminator", "EditionId", "Name" });
            DropIndex("AbpFeatures", new[] { "Discriminator", "TenantId", "Name" });

            DropIndex("AbpEditions", new[] { "Name" });

            DropIndex("AbpLanguageTexts", new[] { "TenantId", "LanguageName", "Source", "Key" });

            DropIndex("AbpLanguages", new[] { "TenantId", "Name" });

            DropIndex("AbpUserOrganizationUnits", new[] { "OrganizationUnitId" });
            DropIndex("AbpUserOrganizationUnits", new[] { "UserId" });
            DropIndex("AbpUserOrganizationUnits", new[] { "TenantId", "OrganizationUnitId" });
            DropIndex("AbpUserOrganizationUnits", new[] { "TenantId", "UserId" });

            DropIndex("AbpOrganizationUnits", new[] { "TenantId", "Code" });
            DropIndex("AbpOrganizationUnits", new[] { "TenantId", "ParentId" });

            DropIndex("AbpAuditLogs", new[] { "TenantId", "ExecutionTime" });
            DropIndex("AbpAuditLogs", new[] { "UserId", "ExecutionTime" });
            DropIndex("AbpPermissions", new[] { "UserId", "Name" });
            DropIndex("AbpPermissions", new[] { "RoleId", "Name" });
            DropIndex("AbpRoles", new[] { "TenantId", "Name" });
            DropIndex("AbpRoles", new[] { "IsDeleted", "TenantId", "Name" });
            DropIndex("AbpSettings", new[] { "TenantId", "Name" });
            DropIndex("AbpSettings", new[] { "UserId", "Name" });
            DropIndex("AbpTenants", new[] { "TenancyName" });
            DropIndex("AbpTenants", new[] { "IsDeleted", "TenancyName" });
            DropIndex("AbpUserLogins", new[] { "UserId", "LoginProvider" });
            DropIndex("AbpUserRoles", new[] { "UserId", "RoleId" });
            DropIndex("AbpUserRoles", new[] { "RoleId" });
            DropIndex("AbpUsers", new[] { "TenantId", "UserName" });
            DropIndex("AbpUsers", new[] { "TenantId", "EmailAddress" });
            DropIndex("AbpUsers", new[] { "IsDeleted", "TenantId", "UserName" });
            DropIndex("AbpUsers", new[] { "IsDeleted", "TenantId", "EmailAddress" });

            CreateIndex("AbpPermissions", new[] { "UserId" });
            CreateIndex("AbpPermissions", new[] { "RoleId" });
            CreateIndex("AbpRoles", new[] { "TenantId" });
            CreateIndex("AbpSettings", new[] { "TenantId" });
            CreateIndex("AbpSettings", new[] { "UserId" });
            CreateIndex("AbpUserLogins", new[] { "UserId" });
            CreateIndex("AbpUserRoles", new[] { "UserId" });
            CreateIndex("AbpUsers", new[] { "TenantId" });
        }
    }
}

```

**Comment by hikalkan** [comment]
Thank you for sharing your solution. It's tested for SQL Server, but not MySQL.
