### ISSUE TITLE
error in appsession.js

### ISSUE THREAD

**Issue by csharpweb** [aspnetboilerplate/module-zero-template#59]
i do not know what happened,i had seen the webtsite http://eventcloud.aspnetboilerplate.com,it is ok in the same code. please help me,thanks.

````js
(function () {
    angular.module('app').factory('appSession', [
            function () {

                var _session = {
                    user: null,
                    tenant: null
                };
               //abp.services is null
                abp.services.app.session.getCurrentLoginInformations({ async: false }).done(function (result) {
                    _session.user = result.user;
                    _session.tenant = result.tenant;
                });

                return _session;
            }
        ]);
})();
````

**Comment by hikalkan** [comment]
What error are you getting?

**Comment by csharpweb** [comment]
angular.js:12520 TypeError: Cannot read property 'app' of undefined
    at Object.<anonymous> (http://localhost:6634/App/Main/services/appSession.js:10:29)
    at Object.e [as invoke] (http://localhost:6634/Scripts/angular.min.js:39:394)
    at Object.$get (http://localhost:6634/Scripts/angular.min.js:37:311)
    at Object.e [as invoke] (http://localhost:6634/Scripts/angular.min.js:39:394)
    at http://localhost:6634/Scripts/angular.min.js:41:224
    at d (http://localhost:6634/Scripts/angular.min.js:39:92)
    at Object.e [as invoke] (http://localhost:6634/Scripts/angular.min.js:39:362)
    at M.instance (http://localhost:6634/Scripts/angular.min.js:80:336)
    at D (http://localhost:6634/Scripts/angular.min.js:61:362)
    at g (http://localhost:6634/Scripts/angular.min.js:55:105) <div ng-include="'/App/Main/views/layout/header.cshtml'" class="ng-scope" data-ng-animate="1">

i had debugged the code, the object of abp.services is null,it caused an error.

**Comment by csharpweb** [comment]
and there has an other error:
angular.js:12520 Error: [$injector:unpr] http://errors.angularjs.org/1.4.8/$injector/unpr?p0=abp.services.app.tenantProvider%20%3C-%20abp.services.app.tenant%20%3C-%20app.views.tenants.index
    at Error (native)
    at http://localhost:6634/Scripts/angular.min.js:6:416
    at http://localhost:6634/Scripts/angular.min.js:41:121
    at Object.d [as get] (http://localhost:6634/Scripts/angular.min.js:39:92)
    at http://localhost:6634/Scripts/angular.min.js:41:195
    at d (http://localhost:6634/Scripts/angular.min.js:39:92)
    at Object.e [as invoke] (http://localhost:6634/Scripts/angular.min.js:39:362)
    at M.instance (http://localhost:6634/Scripts/angular.min.js:80:336)
    at D (http://localhost:6634/Scripts/angular.min.js:61:362)
    at g (http://localhost:6634/Scripts/angular.min.js:55:105) <div ng-view="" ui-view="" class="shuffle-animation col-xs-12 ng-scope" data-ng-animate="1">

i created my project use this template.

**Comment by hikalkan** [comment]
When we test it, the template works. Something you changed probably effected the application. To understand what, can you check logs. It probably writes the exception.

**Comment by csharpweb** [comment]
I already know where the problem is, I have solved this problem, thank you for your help.
