### ISSUE TITLE
No Entity Framework provider found for the ADO.NET provider with invariant name 'Effort.Provider'.

### ISSUE THREAD

**Issue by mahyarmot** [aspnetboilerplate/module-zero-template#71]
Hi,
We are using Asp.net Zero MPA Version.
Everything was going well but suddenly after a clean rebuild action, all the unit tests (even the default unit tests) crashed and not working ! 
In my ideas the exception reason is related to Effort Framework
The exception is : 

Additional information: No Entity Framework provider found for the ADO.NET provider with invariant name 'Effort.Provider'. Make sure the provider is registered in the 'entityFramework' section of the application config file

And the stack-trace is : 
   at System.Data.Entity.Infrastructure.DependencyResolution.DefaultProviderServicesResolver.GetService(Type type, Object key)
   at System.Data.Entity.Infrastructure.DependencyResolution.CachingDependencyResolver.<>c__DisplayClass1.<GetService>b__0(Tuple`2 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Data.Entity.Infrastructure.DependencyResolution.CachingDependencyResolver.GetService(Type type, Object key)
   at System.Data.Entity.Infrastructure.DependencyResolution.ResolverChain.<>c__DisplayClass3.<GetService>b__0(IDbDependencyResolver r)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Data.Entity.Infrastructure.DependencyResolution.ResolverChain.GetService(Type type, Object key)
   at System.Data.Entity.Infrastructure.DependencyResolution.RootDependencyResolver.GetService(Type type, Object key)
   at System.Data.Entity.Infrastructure.DependencyResolution.ResolverChain.<>c__DisplayClass3.<GetService>b__0(IDbDependencyResolver r)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Data.Entity.Infrastructure.DependencyResolution.ResolverChain.GetService(Type type, Object key)
   at System.Data.Entity.Infrastructure.DependencyResolution.CompositeResolver`2.GetService(Type type, Object key)
   at System.Data.Entity.Infrastructure.DependencyResolution.DbDependencyResolverExtensions.GetService[T](IDbDependencyResolver resolver, Object key)
   at System.Data.Entity.Utilities.DbProviderFactoryExtensions.GetProviderServices(DbProviderFactory factory)
   at System.Data.Entity.Infrastructure.DefaultManifestTokenResolver.<>c__DisplayClass1.<ResolveManifestToken>b__0(Tuple`3 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Data.Entity.Infrastructure.DefaultManifestTokenResolver.ResolveManifestToken(DbConnection connection)
   at System.Data.Entity.Utilities.DbConnectionExtensions.GetProviderInfo(DbConnection connection, DbProviderManifest& providerManifest)
   at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
   at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.ForceOSpaceLoadingForKnownEntityTypes()
   at System.Data.Entity.DbContext.System.Data.Entity.Infrastructure.IObjectContextAdapter.get_ObjectContext()
   at Abp.EntityFramework.AbpDbContext.RegisterToChanges() in D:\Halil\GitHub\aspnetboilerplate\src\Abp.EntityFramework\EntityFramework\AbpDbContext.cs:line 140
   at Abp.Zero.EntityFramework.AbpZeroDbContext`3..ctor(DbConnection dbConnection, Boolean contextOwnsConnection) in D:\Halil\GitHub\module-zero\src\Abp.Zero.EntityFramework\Zero\EntityFramework\AbpZeroDbContext.cs:line 81
   at MITD.TMS.EntityFramework.TMSDbContext..ctor(DbConnection dbConnection) in F:\TfsWorkspace\SCTMS\src\Shaar.TMS.EntityFramework\EntityFramework\TMSDbContext.cs:line 49

Thanks, 

![abpunittestappconfig](https://cloud.githubusercontent.com/assets/6184301/20563811/d69842a4-b192-11e6-800f-06e612832226.png)

**Comment by hikalkan** [comment]
I had the same problem a long time ago and fixed it somehow but I can't remember now :(
Can you try to get a previous, running version of your solution from your source control and try it?

**Comment by mahyarmot** [comment]
Dear Halil,
I fixed above error by your solution, but as a result I faced a new issue about the AbpZeroDbContext and Effort. When I creating a new instance of contexts, we have an exception of  "System.InvalidOperationException: Sequence contains no matching element". As I was searching about the exception, I accidentally found out that, if I make a copy of our context and replace the  AbpZeroDbContext<Tenant, Role, User> with DbContext base class, the problem will be solved. 
And at last you need to know that we have added new properties to User Entity, which may cause the problem.
I am going to hear from you :)
